#!/bin/sh

### BEGIN INIT INFO
# Provides:		hostapd
# Required-Start:	$remote_fs
# Required-Stop:	$remote_fs
# Should-Start:		$network
# Should-Stop:
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	Advanced IEEE 802.11 management daemon
# Description:		Userspace IEEE 802.11 AP and IEEE 802.1X/WPA/WPA2/EAP
#			Authenticator
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin
KEEXYBOX_ROOT=/opt/keexybox
HOSTAPD_ROOT=${KEEXYBOX_ROOT}/hostapd
DAEMON_SBIN=${HOSTAPD_ROOT}/usr/local/bin/hostapd
#DAEMON_DEFS=/etc/default/hostapd
DAEMON_CONF=${HOSTAPD_ROOT}/etc/hostapd.conf
NAME=hostapd
DESC="advanced IEEE 802.11 management"
PIDFILE=$HOSTAPD_ROOT/var/run/hostapd.pid

[ -x "$DAEMON_SBIN" ] || exit 0
#[ -s "$DAEMON_DEFS" ] && . /etc/default/hostapd
[ -n "$DAEMON_CONF" ] || exit 0

DAEMON_OPTS="-B -P $PIDFILE $DAEMON_OPTS $DAEMON_CONF"

. /lib/lsb/init-functions

for conf in $DAEMON_CONF
do
    if [ ! -r "$conf" ]
    then
        log_action_msg "hostapd config $conf not found, not starting hostapd."
        exit 1
    fi
done

rc=0

case "$1" in
  start)
	#if [ "$DAEMON_CONF" != /etc/hostapd/hostapd.conf ]
	#then
	#	log_warning_msg "hostapd config not in /etc/hostapd/hostapd.conf -- please read /usr/share/doc/hostapd/NEWS.Debian.gz"
	#fi
	log_daemon_msg "Starting $DESC" "$NAME"
	start-stop-daemon --start --oknodo --quiet --exec "$DAEMON_SBIN" \
		--pidfile "$PIDFILE" -- $DAEMON_OPTS >/dev/null
	rc=$?
	log_end_msg "$rc"
	;;
  stop)
	log_daemon_msg "Stopping $DESC" "$NAME"
	start-stop-daemon --stop --oknodo --quiet --exec "$DAEMON_SBIN" \
		--pidfile "$PIDFILE"
	rc=$?
	log_end_msg "$rc"
	;;
  reload)
    # Reload look to have to effect so reload is implemented as restart
  	$0 stop
	sleep 8
	$0 start
  	#log_daemon_msg "Reloading $DESC" "$NAME"
	#start-stop-daemon --stop --signal HUP --exec "$DAEMON_SBIN" \
	#	--pidfile "$PIDFILE"
	rc=$?
	log_end_msg "$rc"
	;;
  restart|force-reload)
  	$0 stop
	sleep 8
	$0 start
	rc=$?
	log_end_msg "$rc"
	;;
  status)
	status_of_proc "$DAEMON_SBIN" "$NAME"
	exit $?
	;;
  *)
	#N=/etc/init.d/$NAME
	echo "Usage: $0 {start|stop|restart|force-reload|reload|status}" >&2
	exit 1
	;;
esac

#exit 0
exit $rc
