<?php
/**
 * @author Benoit Saglietto <bsaglietto[AT]keexybox.org>
 *
 * @copyright Copyright (c) 2020, Benoit SAGLIETTO
 * @license GPLv3
 *
 * This file is part of Keexybox project.

 * Keexybox is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Keexybox is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Keexybox. If not, see <http://www.gnu.org/licenses/>.
 *
 */

namespace App\Controller\Component;

use Cake\Controller\Component;

/**
 * This component build a list of connection durations proposed to users when connecting
 *
 * @author Benoit SAGLIETTO bsaglietto[@]keexybox.org
 */
class TorComponent extends Component
{
    public function ExitNodesCountryList()
    {
        $countries = [
            '{ac}' => 'Ascension Island',
            '{af}' => 'Afghanistan',
            '{ax}' => 'Aland',
            '{al}' => 'Albania',
            '{dz}' => 'Algeria',
            '{ad}' => 'Andorra',
            '{ao}' => 'Angola',
            '{ai}' => 'Anguilla',
            '{aq}' => 'Antarctica',
            '{ag}' => 'Antigua And Barbuda',
            '{ar}' => 'Argentina Republic',
            '{am}' => 'Armenia',
            '{aw}' => 'Aruba',
            '{au}' => 'Australia',
            '{at}' => 'Austria',
            '{az}' => 'Azerbaijan',
            '{bs}' => 'Bahamas',
            '{bh}' => 'Bahrain',
            '{bd}' => 'Bangladesh',
            '{bb}' => 'Barbados',
            '{by}' => 'Belarus',
            '{be}' => 'Belgium',
            '{bz}' => 'Belize',
            '{bj}' => 'Benin',
            '{bm}' => 'Bermuda',
            '{bt}' => 'Bhutan',
            '{bo}' => 'Bolivia',
            '{ba}' => 'Bosnia And Herzegovina',
            '{bw}' => 'Botswana',
            '{bv}' => 'Bouvet Island',
            '{br}' => 'Brazil',
            '{io}' => 'British Indian Ocean Terr',
            '{vg}' => 'British Virgin Islands',
            '{bn}' => 'Brunei Darussalam',
            '{bg}' => 'Bulgaria',
            '{bf}' => 'Burkina Faso',
            '{bi}' => 'Burundi',
            '{kh}' => 'Cambodia',
            '{cm}' => 'Cameroon',
            '{ca}' => 'Canada',
            '{cv}' => 'Cape Verde',
            '{ky}' => 'Cayman Islands',
            '{cf}' => 'Central African Republic',
            '{td}' => 'Chad',
            '{cl}' => 'Chile',
            '{cn}' => 'People’S Republic Of China',
            '{cx}' => 'Christmas Islands',
            '{cc}' => 'Cocos Islands',
            '{co}' => 'Colombia',
            '{km}' => 'Comoras',
            '{cg}' => 'Congo',
            '{cd}' => 'Congo (Democratic Republic)',
            '{ck}' => 'Cook Islands',
            '{cr}' => 'Costa Rica',
            '{ci}' => 'Cote D Ivoire',
            '{hr}' => 'Croatia',
            '{cu}' => 'Cuba',
            '{cy}' => 'Cyprus',
            '{cz}' => 'Czech Republic',
            '{dk}' => 'Denmark',
            '{dj}' => 'Djibouti',
            '{dm}' => 'Dominica',
            '{do}' => 'Dominican Republic',
            '{tp}' => 'East Timor',
            '{ec}' => 'Ecuador',
            '{eg}' => 'Egypt',
            '{sv}' => 'El Salvador',
            '{gq}' => 'Equatorial Guinea',
            '{ee}' => 'Estonia',
            '{et}' => 'Ethiopia',
            '{fk}' => 'Falkland Islands',
            '{fo}' => 'Faroe Islands',
            '{fj}' => 'Fiji',
            '{fi}' => 'Finland',
            '{fr}' => 'France',
            '{fx}' => 'France Metropolitan',
            '{gf}' => 'French Guiana',
            '{pf}' => 'French Polynesia',
            '{tf}' => 'French Southern Territories',
            '{ga}' => 'Gabon',
            '{gm}' => 'Gambia',
            '{ge}' => 'Georgia',
            '{de}' => 'Germany',
            '{gh}' => 'Ghana',
            '{gi}' => 'Gibralter',
            '{gr}' => 'Greece',
            '{gl}' => 'Greenland',
            '{gd}' => 'Grenada',
            '{gp}' => 'Guadeloupe',
            '{gu}' => 'Guam',
            '{gt}' => 'Guatemala',
            '{gn}' => 'Guinea',
            '{gw}' => 'Guinea-Bissau',
            '{gy}' => 'Guyana',
            '{ht}' => 'Haiti',
            '{hm}' => 'Heard & Mcdonald Island',
            '{hn}' => 'Honduras',
            '{hk}' => 'Hong Kong',
            '{hu}' => 'Hungary',
            '{is}' => 'Iceland',
            '{in}' => 'India',
            '{id}' => 'Indonesia',
            '{ir}' => 'Iran, Islamic Republic Of',
            '{iq}' => 'Iraq',
            '{ie}' => 'Ireland',
            '{im}' => 'Isle Of Man',
            '{il}' => 'Israel',
            '{it}' => 'Italy',
            '{jm}' => 'Jamaica',
            '{jp}' => 'Japan',
            '{jo}' => 'Jordan',
            '{kz}' => 'Kazakhstan',
            '{ke}' => 'Kenya',
            '{ki}' => 'Kiribati',
            '{kp}' => 'Korea, Dem. Peoples Rep Of',
            '{kr}' => 'Korea, Republic Of',
            '{kw}' => 'Kuwait',
            '{kg}' => 'Kyrgyzstan',
            '{la}' => 'Lao People’S Dem. Republic',
            '{lv}' => 'Latvia',
            '{lb}' => 'Lebanon',
            '{ls}' => 'Lesotho',
            '{lr}' => 'Liberia',
            '{ly}' => 'Libyan Arab Jamahiriya',
            '{li}' => 'Liechtenstein',
            '{lt}' => 'Lithuania',
            '{lu}' => 'Luxembourg',
            '{mo}' => 'Macao',
            '{mk}' => 'Macedonia',
            '{mg}' => 'Madagascar',
            '{mw}' => 'Malawi',
            '{my}' => 'Malaysia',
            '{mv}' => 'Maldives',
            '{ml}' => 'Mali',
            '{mt}' => 'Malta',
            '{mh}' => 'Marshall Islands',
            '{mq}' => 'Martinique',
            '{mr}' => 'Mauritania',
            '{mu}' => 'Mauritius',
            '{yt}' => 'Mayotte',
            '{mx}' => 'Mexico',
            '{fm}' => 'Micronesia',
            '{md}' => 'Moldava Republic Of',
            '{mc}' => 'Monaco',
            '{mn}' => 'Mongolia',
            '{me}' => 'Montenegro',
            '{ms}' => 'Montserrat',
            '{ma}' => 'Morocco',
            '{mz}' => 'Mozambique',
            '{mm}' => 'Myanmar',
            '{na}' => 'Namibia',
            '{nr}' => 'Nauru',
            '{np}' => 'Nepal',
            '{an}' => 'Netherlands Antilles',
            '{nl}' => 'Netherlands, The',
            '{nc}' => 'New Caledonia',
            '{nz}' => 'New Zealand',
            '{ni}' => 'Nicaragua',
            '{ne}' => 'Niger',
            '{ng}' => 'Nigeria',
            '{nu}' => 'Niue',
            '{nf}' => 'Norfolk Island',
            '{mp}' => 'Northern Mariana Islands',
            '{no}' => 'Norway',
            '{om}' => 'Oman',
            '{pk}' => 'Pakistan',
            '{pw}' => 'Palau',
            '{ps}' => 'Palestine',
            '{pa}' => 'Panama',
            '{pg}' => 'Papua New Guinea',
            '{py}' => 'Paraguay',
            '{pe}' => 'Peru',
            '{ph}' => 'Philippines (Republic Of The)',
            '{pn}' => 'Pitcairn',
            '{pl}' => 'Poland',
            '{pt}' => 'Portugal',
            '{pr}' => 'Puerto Rico',
            '{qa}' => 'Qatar',
            '{re}' => 'Reunion',
            '{ro}' => 'Romania',
            '{ru}' => 'Russian Federation',
            '{rw}' => 'Rwanda',
            '{ws}' => 'Samoa',
            '{sm}' => 'San Marino',
            '{st}' => 'Sao Tome/Principe',
            '{sa}' => 'Saudi Arabia',
            '{uk}' => 'Scotland',
            '{sn}' => 'Senegal',
            '{rs}' => 'Serbia',
            '{sc}' => 'Seychelles',
            '{sl}' => 'Sierra Leone',
            '{sg}' => 'Singapore',
            '{sk}' => 'Slovakia',
            '{si}' => 'Slovenia',
            '{sb}' => 'Solomon Islands',
            '{so}' => 'Somalia',
            '{as}' => 'Somoa,Gilbert,Ellice Islands',
            '{za}' => 'South Africa',
            '{gs}' => 'South Georgia, South Sandwich Islands',
            '{su}' => 'Soviet Union',
            '{es}' => 'Spain',
            '{lk}' => 'Sri Lanka',
            '{sh}' => 'St. Helena',
            '{kn}' => 'St. Kitts And Nevis',
            '{lc}' => 'St. Lucia',
            '{pm}' => 'St. Pierre And Miquelon',
            '{vc}' => 'St. Vincent & The Grenadines',
            '{sd}' => 'Sudan',
            '{sr}' => 'Suriname',
            '{sj}' => 'Svalbard And Jan Mayen',
            '{sz}' => 'Swaziland',
            '{se}' => 'Sweden',
            '{ch}' => 'Switzerland',
            '{sy}' => 'Syrian Arab Republic',
            '{tw}' => 'Taiwan',
            '{tj}' => 'Tajikistan',
            '{tz}' => 'Tanzania, United Republic Of',
            '{th}' => 'Thailand',
            '{tg}' => 'Togo',
            '{tk}' => 'Tokelau',
            '{to}' => 'Tonga',
            '{tt}' => 'Trinidad And Tobago',
            '{tn}' => 'Tunisia',
            '{tr}' => 'Turkey',
            '{tm}' => 'Turkmenistan',
            '{tc}' => 'Turks And Calcos Islands',
            '{tv}' => 'Tuvalu',
            '{ug}' => 'Uganda',
            '{ua}' => 'Ukraine',
            '{ae}' => 'United Arab Emirates',
            '{uk}' => 'United Kingdom',
            '{us}' => 'United States',
            '{um}' => 'United States Minor Outl.Is.',
            '{uy}' => 'Uruguay',
            '{uz}' => 'Uzbekistan',
            '{vu}' => 'Vanuatu',
            '{va}' => 'Vatican City State',
            '{ve}' => 'Venezuela',
            '{vn}' => 'Viet Nam',
            '{vi}' => 'Virgin Islands (Usa)',
            '{wf}' => 'Wallis And Futuna Islands',
            '{eh}' => 'Western Sahara',
            '{ye}' => 'Yemen',
            '{zm}' => 'Zambia',
            '{zw}' => 'Zimbabwe',
            ];
        return $countries;
    }
}
